version: "3.8"

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: quadtree-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql

  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: quadtree-migration
    volumes:
      - ./database/migration/schema:/flyway/sql

  api:
    build:
      context: ./backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run api/main.go -databaseDatasource="${DATABASE_DATASOURCE}" -port=1991'
    container_name: quadtree-api
    ports:
      - 1991:1991
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
    command: yarn dev
    container_name: quadtree-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - quadtree_node_modules-volume:/app/node_modules
    working_dir: /app

volumes:
  data-volume:
  quadtree_node_modules-volume:
