version: "3.8"

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: quadtree-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql

  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: quadtree-migration
    volumes:
      - ./database/migration/schema:/flyway/sql

volumes:
  data-volume: 
